version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: visits
      - name: facilities
      - name: services
      - name: diagnoses
      - name: population_growth
      - name: capacity
